### ISSUE TITLE
orientation fails to identify points exactly on the line in some cases

### ISSUE THREAD

**Issue by toddwagn** [JuliaGeometry/GeometricalPredicates.jl#12]
julia> orientation(Line(Point(1.,1.), Point(1.8, 1.6)), Point(1.4, 1.3))
1

julia> orientation(Line(Point(1.,1.), Point(1.8, 1.6)), Point(1.4, prevfloat(1.3)))
-1

**Comment by skariel** [comment]
Hi!

Sorry for my late reply I saw this issue just now.

So the result is right, there is no problem at all here (you have to be **VERY** careful when dealing with numerics). Indeed `Point(1.4,1.3)` is to the left of the line and `Point(1.4, prevfloat(1.3))` is to the right. The numerical line is not "continuous" in any way

In fact it is very hard to find points exactly on this line, see code and plot below:

![screenshot from 2016-04-11 12 16 05](https://cloud.githubusercontent.com/assets/2347816/14422449/897f6fc0-ffdf-11e5-8898-e52182694f5a.png)
