### ISSUE TITLE
Possible bug in intriangle.

### ISSUE THREAD

**Issue by KristofferC** [JuliaGeometry/GeometricalPredicates.jl#13]
Let's define a triangle with two vertices on the x-axis:

```jl
a = Point(0.0, 0.0)
b = Point(0.0175751,0.0)
c = Point(0.0110023,0.0115932)

tri = Primitive(a, b, c)
```

Clearly any point on the x axis between the x-coordinate of a and b should be on the triangle and `intriangle` should return a positive number.

However, only points with an x-axis of less than `b.x / 2.0`  return a positive number:

```jl
# Slightly to the left of b.x / 2.0
julia> intriangle(tre, Point(getx(b) / 2.0 - 1e-7, 0.0))
4

# Slightly to the right of b.x / 2.0
julia> intriangle(tre, Point(getx(b) / 2.0 + 1e-7, 0.0))
-1
```

Here are for example two points that show different value for `intriangle` and the triangle:

![figure_2](https://cloud.githubusercontent.com/assets/1282691/14460740/6cf09952-00bf-11e6-803f-13400757b710.png)

**Comment by skariel** [comment]
hi, sorry for the late reply I just saw this issue now

So -- there is no bug here: the algorithms work with numbers between `max_coord` and `min_coord` which are in the range `1.0<=x<2.0` as explained in the [README](https://github.com/JuliaGeometry/GeometricalPredicates.jl/blob/master/README.md). 

When moving the same test case inside this region the problem disappears, see image below:

![screenshot from 2016-04-15 21 41 21](https://cloud.githubusercontent.com/assets/2347816/14571671/3413d4fa-0353-11e6-944c-bd5b18c2d74c.png)

**Comment by KristofferC** [comment]
Thanks for the answer. I should have read the README more carefully, I thought the part about `1<=x<=2` was only used internally.

**Comment by skariel** [comment]
note that it's `1<=x<2`, the number `2` is not included in the range
