### ISSUE TITLE
Problems on Travis

### ISSUE THREAD

**Issue by robertdj** [JuliaGeometry/GeometricalPredicates.jl#20]
I'm experiencing a weird problem with the testing on Travis. 

GeometricalPredicates imports `!` from Base. It used to be with `import Base.!` that does not work in Julia v0.5, but recently it was changed to `import Base: !` that works in both Julia v0.4 and v0.5.

On my local, newly compiled Julia v0.5 with a freshly added GeometricalPredicates everything works as expected, but when testing the VoronoiCells package on [Travis](https://travis-ci.org/JuliaGeometry/VoronoiCells.jl/jobs/162133368) it fails for Julia v0.5 because 

> ERROR: LoadError: syntax: invalid operator ".!" (Line 366)

I updated the `REQUIRE` for VoronoiCells to explicitly include GeometricalPredicates v0.0.5, but this did not help. The only directly required package is VoronoiDelaunay.

Have I overlooked something?

**Comment by robertdj** [comment]
I think I have identified the issue. The tag `v0.0.5` is later than `v0.05` (that does **not** import `!` correctly), but when adding the latest version of GeometricalPredicates `v0.05` is checked out -- maybe it is interpreted as `v0.5`?

@skariel : Is it possible to delete the tag `v0.05`?

**Comment by skariel** [comment]
done!

**Comment by robertdj** [comment]
Thanks! The `v0.05` tag is not seen in this GitHub repo, but it is still the version checked out when running `Pkg.add("GeometricalPredicates")` and also the version used on Travis.
For now, I get a successful run on Travis with a `Pkg.checkout("GeometricalPredicates")`.

Unfortunately, I don't have the Git(Hub) skills to figure out how fix this tagging issue.

**Comment by robertdj** [comment]
BTW this issue is also causing the VoronoiDelaunay tests to fail at Travis.

**Comment by robertdj** [comment]
@tkelman : I hope it's okay to ask for your help? You seem to know everything about Julia packages.

`GeometricalPredicates` has/had a tag called `v0.05` with only one `.` that does not work on Julia v0.5. The latest tag is `v0.0.5` with two `.` and this works on Julia v0.5. 

Unfortunately, `Pkg.add("GeometricalPredicates")` checks out the `v0.05` and so does e.g. `Pkg.add("VoronoiDelaunay")` whose `REQUIRE` file contains the line:

> GeometricalPredicates 0.0.5

The [releases](https://github.com/JuliaGeometry/GeometricalPredicates.jl/releases) and (as far as I can tell) `METADATA` no longer contain a `v0.05`.

Do you know how to fix this issue?

**Comment by tkelman** [comment]
Strange. I don't see it in METADATA (https://github.com/JuliaLang/METADATA.jl/tree/metadata-v2/GeometricalPredicates/versions) or in the tags. What does your `Pkg.status()`, and `git status` inside `Pkg.dir("METADATA")` say?

**Comment by robertdj** [comment]
I wiped `~/.julia/v0.5` and `~/.julia/lib/v0.5` to start on a clean slate. First 3 commands after this:

> julia> Pkg.update()
> INFO: Initializing package repository /home/robert/.julia/v0.5
> INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
> INFO: Updating METADATA...
> INFO: Computing changes...
> INFO: No packages to install, update or remove
> 
> julia> Pkg.add("GeometricalPredicates")
> INFO: Installing Compat v0.9.2
> INFO: Installing GeometricalPredicates v0.0.5
> INFO: Package database updated
> 
> julia> Pkg.status()
> 1 required packages:
>  - GeometricalPredicates         0.0.5
> 1 additional packages:
>  - Compat                        0.9.2
> 

The output of `git status` in `~/.julia/v0.5/METADATA`: 

> $ git status
> On branch metadata-v2
> Your branch is up-to-date with 'origin/metadata-v2'.
> 
> nothing to commit, working directory clean

In `~/.julia/v0.5/GeometricalPredicates`:

> $ git tag
> v0.0.1
> v0.0.2
> v0.0.4
> v0.05

**Comment by robertdj** [comment]
BTW: Running `Pkg.checkout("GeometricalPredicates")` adds a `v0.0.5` tag in `~/.julia/v0.5/GeometricalPredicates` and the package then works.

**Comment by tkelman** [comment]
Hm, interesting. I see the git tag too, but only in a clone that's been around for a while. The bad tag must've been deleted since then. Try deleting `~/.julia/.cache/GeometricalPredicates` and `~/.julia/v0.5/GeometricalPredicates` then running `Pkg.resolve()` ?

**Comment by tkelman** [comment]
Pkg typically only works based on git sha's rather than tag names, so I'm not sure exactly what was happening.

**Comment by robertdj** [comment]
After deleting the `.cache` folder the `v0.05` tag is gone, but installing GeometricalPredicates again the chekced out commit is still the one that *used* to have the `v0.05` tag.

> julia> Pkg.resolve()
> INFO: No packages to install, update or remove

In the shell: 

> $ git tag
> v0.0.1
> v0.0.2
> v0.0.4
> v0.0.5

**Comment by tkelman** [comment]
I see 916081fd59a2690bd3fb9e55506111e2ae8fa338, which is the tagged commit in https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/GeometricalPredicates/versions/0.0.5/sha1 - which commit are you seeing?

**Comment by robertdj** [comment]
The same. But this is from 2016-07-12 (a pull request from you) and not tagged with `v0.0.5` on my machine (using `gitk`). 
If you checkout the master branch you see the 'real' `v0.0.5` from 2016-09-13 (commit b85654e381859fd933b31919f526a843c353e6a2).

**Comment by tkelman** [comment]
Like I said, Julia Pkg doesn't use git tags, only the metadata information. They should usually match, but here it looks like they don't.

**Comment by robertdj** [comment]
Right. Is there a way to fix this?

**Comment by tkelman** [comment]
Delete the 0.0.5 git tag, replace it with the same sha as the metadata 0.0.5 tag. Make a new 0.0.6 git and metadata tag, from the same commit, and open a METADATA PR. If it drops support for Julia 0.4 then it should be 0.1.0 instead.

**Comment by tkelman** [comment]
Oh and before making a new metadata tag, best to add a minimum version dependency on your Compat requirement that corresponds to the newest features you're using.

**Comment by tkelman** [comment]
Not sure if you're using anything that doesn't go through the `@compat` macro here but you might be able to just drop the Compat requirement and that one use of the macro. Would need to test that though.

**Comment by robertdj** [comment]
Great -- thanks a lot for your help! 
@skariel : Do you want to be in charge of the tagging?

**Comment by skariel** [comment]
@robertdj I prefer not, can you do this?

**Comment by robertdj** [comment]
Sure.

**Comment by skariel** [comment]
Thanks, I sent you an invite to be a collaborator with write access, the should do right?

**Comment by robertdj** [comment]
I think so. 
@tkelman : Just to make sure I'm not screwing this up. 

- In the shell (the commit is the one you mentioned above):
```
git tag -d v0.0.5
git tag v0.0.5 916081fd59a2690bd3fb9e55506111e2ae8fa338
```
- Update `REQUIRE` file with Compat version/remove `@compat` dependency.
- In Julia: `Pkg.tag("GeometricalPredicates")`
- Push to this repo and open PR.

**Comment by tkelman** [comment]
`tag -d` will only delete the tag locally. I think it's `git push origin :v0.0.5` to delete the tag here on the remote.

**Comment by robertdj** [comment]
I've made the updates and Travis is satisfied.

**Comment by skariel** [comment]
@robertdj sure, please go ahead with the PR

**Comment by robertdj** [comment]
@skariel : The issues with GeometricalPredicates should be fixed, but awaits approval. 
I added the latest version of the Colors to `REQUIRE` -- would you prefer a lower version?
I am making a PR for VororoniDelaunay later today, but I *think* you have to run the `PkgDev.tag("VoronoiDelaunay")` and submit as I don't have write access to the VD repo.
