### ISSUE TITLE
Cast ints as floats?

### ISSUE THREAD

**Issue by alainchau** [JuliaGeometry/GeometricalPredicates.jl#33]
I forgot to use floats instead of ints and stumbled upon the following:
```julia
a = Point(0, 0)
b = Point(1, 1)
l = Line(a, b)

orientation(l, Point(0, 0))
# 0

orientation(l, Point(0, 0.))
# 1

orientation(l, Point(2, 2))
# -1
```

Should it give a warning/error when given ints?

**Comment by dkarrasch** [comment]
Would this https://github.com/JuliaGeometry/GeometricalPredicates.jl/issues/22#issuecomment-533884355 help solve the problem? The result of `Point` with two `Int`s is probably far from what you would expect when interpreting the arguments as Cartesian coordinates.

**Comment by alainchau** [comment]
Agree, that would be a nice change!
