### ISSUE TITLE
What does -3 returned from function intriangle means

### ISSUE THREAD

**Issue by jstarczewski** [JuliaGeometry/GeometricalPredicates.jl#38]
Documentation only explains what `-1`, `-2`, and `-4` mean. 
Example code:
```Julia
julia> trb = Primitive(Point2D(1.6068, 1.0115), Point2D(1.157, 1.8638), Point2D(1.5, 1.0))
GeometricalPredicates.UnOrientedTriangle{Point2D}(Point2D(1.6068, 1.0115), Point2D(1.157, 1.8638), Point2D(1.5, 1.0), -0.4498, 0.8522999999999998, -0.1068, -0.011500000000000066, -0.020514711322000057, 0.09399892044199996, -0.09619834000000002, 1)

julia> pp = Point2D(1.6, 1.0392)
Point2D(1.6, 1.0392)

julia> intriangle(trb, pp)
-3
```
@skariel I know it's been a long time since you've updated this section of README.md in commit `b8a7abfca01b723d0cfb39e8c743dd2368f0afb3`, but maybe you can help me?

**Comment by skariel** [comment]
Hi @jstarczewski, the point is outside in front of vertices 'c'. The readme says so, albeit with a typo: -4 instead of -3. I'll leave this issue open until the typo in readme is fixed
